# Sample .travis.yml for R projects

language: r
r: bioc-devel
dist: trusty

cache: packages

warnings_are_errors: false 
group: deprecated-2017Q3
sudo: required


bioc_required: true

before_install:
  - R -e 'install.packages("devtools")'


install:
  - R -e 'devtools::install_deps(dep = T,type="binary")'
  - R -e 'devtools::install_github("RGLab/flowCore",ref="trunk")'
  - R -e 'devtools::install_github("RGLab/ncdfFlow",ref="trunk")'
  - R -e 'devtools::install_github("RGLab/cytolib",ref="trunk")'
  
env:
 global:
   - CRAN: http://cran.rstudio.com
-apt_packages:
-  - libhdf5-7 
-  - libhdf5-dev

notifications:
  email:
    on_success: change
    on_failure: change
