language: r
warnings_are_errors: false
env:
  global:
    - BIOC_USE_DEVEL="TRUE"
bioc_required: true
apt_packages:
  - libhdf5-7 
  - libhdf5-dev
  - r-bioc-rgraphviz
  - r-bioc-rbgl
  - r-bioc-zlibbioc
  - r-bioc-graph
  - r-bioc-biobase	
r_binary_packages:
  - testthat
  - RcppArmadillo
  - DEoptimR
  - corpcor
  - hexbin
  - IDPmisc
  - reshape2
  - markdown
  - XML
  - robustbase
  - data.table
  - knitr
  - pcaPP
  - rrcov
# - RBGL
# - zlibbioc
# - graph
# - Rgraphviz	
branches:
  only:
    - travis 
notifications:
  email:
    on_success: change
    on_failure: change
