# Sample .travis.yml for R projects

language: r
r: bioc-devel
dist: xenial

cache: packages

warnings_are_errors: false 
sudo: required


bioc_required: true

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("BiocManager")'
  - R -e 'devtools::install_github("Bioconductor/BiocGenerics", ref = "master")'


install:
  - R -e 'BiocManager::install("Rhdf5lib")'
  - R -e 'install.packages("testthat")'
  - R -e 'install.packages("knitr")'
  - R -e 'install.packages("parallel")'
  - R -e 'devtools::install_github("FredHutch/cytolib", ref="cytoset", auth_token=Sys.getenv("CI_USER_TOKEN"))'
  - R -e 'devtools::install_github("RcppCore/RcppParallel", ref="master")'
  - R -e 'devtools::install_github("RGLab/RProtoBufLib", ref="cytoset")'
  - R -e 'devtools::install_github("RGLab/flowCore",ref="trunk", auth_token=Sys.getenv("CI_USER_TOKEN"))'
  - R -e 'devtools::install_github("RGLab/ncdfFlow",ref="trunk")'
  - R -e 'devtools::install_github("RGLab/flowWorkspaceData", ref="cytoset")'
  - R -e 'devtools::install_deps(upgrade = "Always")'

script:
  - R CMD build . --no-build-vignettes
  - R -e 'install.packages(list.files(pattern="*tar.gz"), repos=NULL, type="source")'
  - R -e 'devtools::install_github("RGLab/CytoML", ref="cytoset", auth_token=Sys.getenv("CI_USER_TOKEN"))'
  - R -e 'devtools::install_github("RGLab/ggcyto", ref="trunk")'
  - R CMD build .
  - R CMD check *tar.gz

env:
 global:
   - CRAN: http://cran.rstudio.com
   - secure: HFnxefnfMuyddSduRz0p8duWMxZM+8xSKhGwW08IyVfBvRRkqAaI6pT4OUl1xkXViS2N0Grjcvhglor5s3H5wux5HGl3W2pWm7PAVHNkDwA1NjwCQs7bZPQUCZdrLXY8IqYbd7hEH3dQcRix5lYt2WcmuRj4b8N3MWW/GVamu70=
-apt_packages:
-  - libhdf5-7 
-  - libhdf5-dev

notifications:
  email:
    on_success: change
    on_failure: change
