# Sample .travis.yml for R projects

language: r
r: bioc-devel
dist: trusty

cache: packages

warnings_are_errors: true
sudo: false

bioc_required: true

env:
 global:
   - CRAN: http://cran.rstudio.com
-apt_packages:
-  - libhdf5-7 
-  - libhdf5-dev

notifications:
  email:
    on_success: change
    on_failure: change
