# Sample .travis.yml for R projects

language: r
r: devel
dist: trusty

cache: packages

warnings_are_errors: false 
sudo: required


bioc_required: true

before_install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_github("Bioconductor/BiocGenerics", ref = "master")'


install:
  - R -e 'devtools::install_deps(upgrade = "always")'
  - R -e 'install.packages("testthat")'
  - R -e 'install.packages("knitr")'
  - R -e 'install.packages("parallel")'
  - R -e 'devtools::install_github("RGLab/flowWorkspaceData", ref="trunk")'
  - R -e 'devtools::install_github("RGLab/cytolib",ref="trunk")'
  - R -e 'devtools::install_github("RGLab/RProtoBufLib", ref = "trunk")'
  - R -e 'devtools::install_github("RGLab/flowCore", ref="trunk")'
  - R -e 'devtools::install_github("RGLab/ncdfFlow", ref="trunk")'
  
script:
  - R CMD build . --no-build-vignettes
  - R -e 'install.packages(list.files(pattern="*tar.gz"), repos=NULL, type="source")'
  - R -e 'devtools::install_github("RGLab/CytoML", ref="trunk")'
  - R -e 'devtools::install_github("RGLab/ggcyto", ref="trunk")'
  - R CMD build .
  - R CMD check *tar.gz

env:
 global:
   - CRAN: http://cran.rstudio.com
-apt_packages:
-  - libhdf5-7 
-  - libhdf5-dev

notifications:
  email:
    on_success: change
    on_failure: change
